version: "3"

services:
  assignment-1:
    build:
      dockerfile: Dockerfile
      context: ./assignment1

  assignment-2:
    build:
      dockerfile: Dockerfile
      context: ./assignment2
    depends_on:
      - assignment-1

  assignment-3:
    build:
      dockerfile: Dockerfile
      context: ./assignment3
    depends_on:
      - assignment-2

  assignment-4:
    build:
      dockerfile: Dockerfile
      context: ./assignment4
    depends_on:
      - assignment-3
